// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: wzyWatch

#ifndef _WZYWATCH_UI_H
#define _WZYWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_humi;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_wzy_png);    // assets\wzy.png

LV_FONT_DECLARE(ui_font_day);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
